apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devsecops
  namespace: argocd
spec:
  description: "DevSecOps Pipeline Project"

  # WHY: Only allow syncing from your repo — prevents rogue sources
  sourceRepos:
    - "https://github.com/IdrisShaik/Devops_Project.git"

  # Only allow deploying to the devsecops namespace in this cluster
  destinations:
    - namespace: devsecops
      server:    https://kubernetes.default.svc

  # Allow all core K8s resources
  clusterResourceWhitelist:
    - group: ""
      kind:  Namespace

  namespaceResourceWhitelist:
    - group: "apps"
      kind:  Deployment
    - group: ""
      kind:  Service
    - group: ""
      kind:  ConfigMap
    - group: "networking.k8s.io"
      kind:  Ingress
    - group: "autoscaling"
      kind:  HorizontalPodAutoscaler
    - group: ""
      kind:  ServiceAccount
